// flow-typed signature: 8da8649cde7e433ccfab3b776be3b79b
// flow-typed version: <<STUB>>/bn.js_v^5.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bn.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bn.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bn.js/lib/bn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bn.js/lib/bn.js' {
  declare module.exports: $Exports<'bn.js/lib/bn'>;
}
