// flow-typed signature: 8dedcebf9a48fa95d40824e83a7eef7d
// flow-typed version: <<STUB>>/buffer_v6.0.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'buffer/index' {
  declare module.exports: $Exports<'buffer'>;
}
declare module 'buffer/index.js' {
  declare module.exports: $Exports<'buffer'>;
}
