// flow-typed signature: 1d431fcaaa378246e77473538c349228
// flow-typed version: <<STUB>>/buffer-layout_v^1.2.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer-layout/jsdoc/custom/local' {
  declare module.exports: any;
}

declare module 'buffer-layout/lib/Layout' {
  declare module.exports: any;
}

declare module 'buffer-layout/test/examples' {
  declare module.exports: any;
}

declare module 'buffer-layout/test/LayoutTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buffer-layout/jsdoc/custom/local.js' {
  declare module.exports: $Exports<'buffer-layout/jsdoc/custom/local'>;
}
declare module 'buffer-layout/lib/Layout.js' {
  declare module.exports: $Exports<'buffer-layout/lib/Layout'>;
}
declare module 'buffer-layout/test/examples.js' {
  declare module.exports: $Exports<'buffer-layout/test/examples'>;
}
declare module 'buffer-layout/test/LayoutTest.js' {
  declare module.exports: $Exports<'buffer-layout/test/LayoutTest'>;
}
