// flow-typed signature: bd59b655ec89c675a5f5c2188a37c49d
// flow-typed version: <<STUB>>/crypto-hash_v1.2.2/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crypto-hash/browser' {
  declare module.exports: any;
}

declare module 'crypto-hash/thread' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crypto-hash/browser.js' {
  declare module.exports: $Exports<'crypto-hash/browser'>;
}
declare module 'crypto-hash/index' {
  declare module.exports: $Exports<'crypto-hash'>;
}
declare module 'crypto-hash/index.js' {
  declare module.exports: $Exports<'crypto-hash'>;
}
declare module 'crypto-hash/thread.js' {
  declare module.exports: $Exports<'crypto-hash/thread'>;
}
