// flow-typed signature: 3f5253ee300391e662d9c724d020a98e
// flow-typed version: <<STUB>>/js-sha3_v^0.8.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-sha3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-sha3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-sha3/build/sha3.min' {
  declare module.exports: any;
}

declare module 'js-sha3/src/sha3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-sha3/build/sha3.min.js' {
  declare module.exports: $Exports<'js-sha3/build/sha3.min'>;
}
declare module 'js-sha3/src/sha3.js' {
  declare module.exports: $Exports<'js-sha3/src/sha3'>;
}
