// flow-typed signature: e6c04a408e31a0534a8f15ba158400d1
// flow-typed version: <<STUB>>/mockttp_v^1.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockttp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockttp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockttp/dist/client/introspection-query' {
  declare module.exports: any;
}

declare module 'mockttp/dist/client/mocked-endpoint-client' {
  declare module.exports: any;
}

declare module 'mockttp/dist/client/mockttp-client' {
  declare module.exports: any;
}

declare module 'mockttp/dist/main-browser' {
  declare module.exports: any;
}

declare module 'mockttp/dist/main' {
  declare module.exports: any;
}

declare module 'mockttp/dist/mockttp' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/base-rule-builder' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/completion-checkers' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/matchers' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/requests/request-handlers' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/requests/request-rule-builder' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/requests/request-rule' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/rule-serialization' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/websockets/websocket-handlers' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/websockets/websocket-rule-builder' {
  declare module.exports: any;
}

declare module 'mockttp/dist/rules/websockets/websocket-rule' {
  declare module.exports: any;
}

declare module 'mockttp/dist/server/http-combo-server' {
  declare module.exports: any;
}

declare module 'mockttp/dist/server/mocked-endpoint' {
  declare module.exports: any;
}

declare module 'mockttp/dist/server/mockttp-server' {
  declare module.exports: any;
}

declare module 'mockttp/dist/standalone/mockttp-standalone' {
  declare module.exports: any;
}

declare module 'mockttp/dist/standalone/standalone-bin' {
  declare module.exports: any;
}

declare module 'mockttp/dist/standalone/standalone-model' {
  declare module.exports: any;
}

declare module 'mockttp/dist/types' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/destroyable-server' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/fs' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/normalize-url' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/promise' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/request-utils' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/serialization' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/socket-util' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/tls' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/type-utils' {
  declare module.exports: any;
}

declare module 'mockttp/dist/util/util' {
  declare module.exports: any;
}

declare module 'mockttp/docs/runkitExample' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockttp/dist/client/introspection-query.js' {
  declare module.exports: $Exports<'mockttp/dist/client/introspection-query'>;
}
declare module 'mockttp/dist/client/mocked-endpoint-client.js' {
  declare module.exports: $Exports<'mockttp/dist/client/mocked-endpoint-client'>;
}
declare module 'mockttp/dist/client/mockttp-client.js' {
  declare module.exports: $Exports<'mockttp/dist/client/mockttp-client'>;
}
declare module 'mockttp/dist/main-browser.js' {
  declare module.exports: $Exports<'mockttp/dist/main-browser'>;
}
declare module 'mockttp/dist/main.js' {
  declare module.exports: $Exports<'mockttp/dist/main'>;
}
declare module 'mockttp/dist/mockttp.js' {
  declare module.exports: $Exports<'mockttp/dist/mockttp'>;
}
declare module 'mockttp/dist/rules/base-rule-builder.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/base-rule-builder'>;
}
declare module 'mockttp/dist/rules/completion-checkers.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/completion-checkers'>;
}
declare module 'mockttp/dist/rules/matchers.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/matchers'>;
}
declare module 'mockttp/dist/rules/requests/request-handlers.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/requests/request-handlers'>;
}
declare module 'mockttp/dist/rules/requests/request-rule-builder.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/requests/request-rule-builder'>;
}
declare module 'mockttp/dist/rules/requests/request-rule.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/requests/request-rule'>;
}
declare module 'mockttp/dist/rules/rule-serialization.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/rule-serialization'>;
}
declare module 'mockttp/dist/rules/websockets/websocket-handlers.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/websockets/websocket-handlers'>;
}
declare module 'mockttp/dist/rules/websockets/websocket-rule-builder.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/websockets/websocket-rule-builder'>;
}
declare module 'mockttp/dist/rules/websockets/websocket-rule.js' {
  declare module.exports: $Exports<'mockttp/dist/rules/websockets/websocket-rule'>;
}
declare module 'mockttp/dist/server/http-combo-server.js' {
  declare module.exports: $Exports<'mockttp/dist/server/http-combo-server'>;
}
declare module 'mockttp/dist/server/mocked-endpoint.js' {
  declare module.exports: $Exports<'mockttp/dist/server/mocked-endpoint'>;
}
declare module 'mockttp/dist/server/mockttp-server.js' {
  declare module.exports: $Exports<'mockttp/dist/server/mockttp-server'>;
}
declare module 'mockttp/dist/standalone/mockttp-standalone.js' {
  declare module.exports: $Exports<'mockttp/dist/standalone/mockttp-standalone'>;
}
declare module 'mockttp/dist/standalone/standalone-bin.js' {
  declare module.exports: $Exports<'mockttp/dist/standalone/standalone-bin'>;
}
declare module 'mockttp/dist/standalone/standalone-model.js' {
  declare module.exports: $Exports<'mockttp/dist/standalone/standalone-model'>;
}
declare module 'mockttp/dist/types.js' {
  declare module.exports: $Exports<'mockttp/dist/types'>;
}
declare module 'mockttp/dist/util/destroyable-server.js' {
  declare module.exports: $Exports<'mockttp/dist/util/destroyable-server'>;
}
declare module 'mockttp/dist/util/fs.js' {
  declare module.exports: $Exports<'mockttp/dist/util/fs'>;
}
declare module 'mockttp/dist/util/normalize-url.js' {
  declare module.exports: $Exports<'mockttp/dist/util/normalize-url'>;
}
declare module 'mockttp/dist/util/promise.js' {
  declare module.exports: $Exports<'mockttp/dist/util/promise'>;
}
declare module 'mockttp/dist/util/request-utils.js' {
  declare module.exports: $Exports<'mockttp/dist/util/request-utils'>;
}
declare module 'mockttp/dist/util/serialization.js' {
  declare module.exports: $Exports<'mockttp/dist/util/serialization'>;
}
declare module 'mockttp/dist/util/socket-util.js' {
  declare module.exports: $Exports<'mockttp/dist/util/socket-util'>;
}
declare module 'mockttp/dist/util/tls.js' {
  declare module.exports: $Exports<'mockttp/dist/util/tls'>;
}
declare module 'mockttp/dist/util/type-utils.js' {
  declare module.exports: $Exports<'mockttp/dist/util/type-utils'>;
}
declare module 'mockttp/dist/util/util.js' {
  declare module.exports: $Exports<'mockttp/dist/util/util'>;
}
declare module 'mockttp/docs/runkitExample.js' {
  declare module.exports: $Exports<'mockttp/docs/runkitExample'>;
}
