// flow-typed signature: 010ed80dfa77343a07cd101a9453f460
// flow-typed version: <<STUB>>/secp256k1_v^4.0.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'secp256k1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'secp256k1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'secp256k1/bindings' {
  declare module.exports: any;
}

declare module 'secp256k1/elliptic' {
  declare module.exports: any;
}

declare module 'secp256k1/lib/elliptic' {
  declare module.exports: any;
}

declare module 'secp256k1/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'secp256k1/bindings.js' {
  declare module.exports: $Exports<'secp256k1/bindings'>;
}
declare module 'secp256k1/elliptic.js' {
  declare module.exports: $Exports<'secp256k1/elliptic'>;
}
declare module 'secp256k1/index' {
  declare module.exports: $Exports<'secp256k1'>;
}
declare module 'secp256k1/index.js' {
  declare module.exports: $Exports<'secp256k1'>;
}
declare module 'secp256k1/lib/elliptic.js' {
  declare module.exports: $Exports<'secp256k1/lib/elliptic'>;
}
declare module 'secp256k1/lib/index' {
  declare module.exports: $Exports<'secp256k1/lib'>;
}
declare module 'secp256k1/lib/index.js' {
  declare module.exports: $Exports<'secp256k1/lib'>;
}
