// flow-typed signature: 93e1c7b898500d4a0bfe05d7e7bdd0b9
// flow-typed version: <<STUB>>/superstruct_v^0.8.3/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superstruct'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superstruct' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superstruct/lib/index.es' {
  declare module.exports: any;
}

declare module 'superstruct/lib' {
  declare module.exports: any;
}

declare module 'superstruct/umd/superstruct' {
  declare module.exports: any;
}

declare module 'superstruct/umd/superstruct.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superstruct/lib/index.es.js' {
  declare module.exports: $Exports<'superstruct/lib/index.es'>;
}
declare module 'superstruct/lib/index' {
  declare module.exports: $Exports<'superstruct/lib'>;
}
declare module 'superstruct/lib/index.js' {
  declare module.exports: $Exports<'superstruct/lib'>;
}
declare module 'superstruct/umd/superstruct.js' {
  declare module.exports: $Exports<'superstruct/umd/superstruct'>;
}
declare module 'superstruct/umd/superstruct.min.js' {
  declare module.exports: $Exports<'superstruct/umd/superstruct.min'>;
}
