// flow-typed signature: 607d90b805d229d69250b382713c4087
// flow-typed version: <<STUB>>/tweetnacl_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tweetnacl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tweetnacl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tweetnacl/nacl-fast' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl-fast.min' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tweetnacl/nacl-fast.js' {
  declare module.exports: $Exports<'tweetnacl/nacl-fast'>;
}
declare module 'tweetnacl/nacl-fast.min.js' {
  declare module.exports: $Exports<'tweetnacl/nacl-fast.min'>;
}
declare module 'tweetnacl/nacl.js' {
  declare module.exports: $Exports<'tweetnacl/nacl'>;
}
declare module 'tweetnacl/nacl.min.js' {
  declare module.exports: $Exports<'tweetnacl/nacl.min'>;
}
