#!/usr/bin/env bash

# shellcheck source=ci/rust-version.sh
here=$(dirname "$0")

source "${here}"/ci/rust-version.sh all

toolchain=
case "$1" in
  stable)
    # shellcheck disable=SC2054 # rust_stable is sourced from rust-version.sh
    toolchain="$rust_stable"
    shift
    ;;
  nightly)
    # shellcheck disable=SC2054 # rust_nightly is sourced from rust-version.sh
    toolchain="$rust_nightly"
    shift
    ;;
  +*)
    toolchain="${1#+}"
    shift
    ;;
  *)
    # shellcheck disable=SC2054 # rust_stable is sourced from rust-version.sh
    toolchain="$rust_stable"
    ;;
esac

set -x
exec cargo "+${toolchain}" "${@}"
