/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_stakeaccount_free(a: number): void;
export function __wbg_get_stakeaccount_meta(a: number): number;
export function __wbg_set_stakeaccount_meta(a: number, b: number): void;
export function __wbg_get_stakeaccount_stake(a: number): number;
export function __wbg_set_stakeaccount_stake(a: number, b: number): void;
export function __wbg_get_stakeaccount_state(a: number): number;
export function __wbg_set_stakeaccount_state(a: number, b: number): void;
export function stakeaccount_fromAccountData(a: number, b: number): number;
export function stakeaccount_displayState(a: number, b: number): void;
export function __wbg_lockup_free(a: number): void;
export function __wbg_get_lockup_custodian(a: number): number;
export function __wbg_set_lockup_custodian(a: number, b: number): void;
export function lockup_unix_timestamp(a: number): number;
export function lockup_epoch(a: number): number;
export function __wbg_pubkey_free(a: number): void;
export function pubkey_toBase58(a: number, b: number): void;
export function __wbg_authorized_free(a: number): void;
export function __wbg_get_authorized_staker(a: number): number;
export function __wbg_set_authorized_staker(a: number, b: number): void;
export function __wbg_get_authorized_withdrawer(a: number): number;
export function __wbg_set_authorized_withdrawer(a: number, b: number): void;
export function __wbg_meta_free(a: number): void;
export function __wbg_get_meta_authorized(a: number): number;
export function __wbg_set_meta_authorized(a: number, b: number): void;
export function __wbg_get_meta_lockup(a: number): number;
export function __wbg_set_meta_lockup(a: number, b: number): void;
export function meta_rent_exempt_reserve(a: number): number;
export function __wbg_stake_free(a: number): void;
export function __wbg_get_stake_delegation(a: number): number;
export function __wbg_set_stake_delegation(a: number, b: number): void;
export function stake_credits_observed(a: number): number;
export function __wbg_delegation_free(a: number): void;
export function delegation_voter_pubkey(a: number): number;
export function delegation_stake(a: number): number;
export function delegation_isBootstrapStake(a: number): number;
export function delegation_isDeactivated(a: number): number;
export function delegation_activation_epoch(a: number): number;
export function delegation_deactivation_epoch(a: number): number;
export function delegation_warmup_cooldown_rate(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
